<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About Us' => 'درباره ما',
    'Consultant' => 'مشاور',
    'Dashboard' => 'داشبورد',
    'Email Enquiry' => 'ایمیل تحقیق',
    'Live Chat' => 'چت زنده',
    'Logout' => 'خروج',
    'My Profile' => 'مشخصات من',
    'My Tasks' => 'وظایف من',
    'Others' => 'دیگران',
    'Packages' => 'بسته ها',
    'Programs' => 'برنامه ها',
    'Shortlisted Courses' => 'دوره های آموزشی',
    'Shortlisted Universities' => 'دانشگاه های برتر',
    'Sign Up' => 'ثبت نام',
    'Standard Tests' => 'تست استاندارد',
    'Students' => 'دانش آموزان',
    'Universities' => 'دانشگاه',
];
