<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A comprehensive search engine with the most updated information on courses and universities, allowing you to find information about schools across the world on a single platform.' => '',
    'About Us' => '',
    'Access to free advice from our consultants regarding availability of scholarships and financial aid.' => '',
    'Access to the student dashboard, where you can shortlist universities/programs, complete online applications, upload the necessary documents, as well as communicate with the respective consultants through video and text chat.' => '',
    'Access to university and other expert speaker webinars through our portal which will help you make a right decision about your higher education choices.' => '',
    'Back To Top' => '',
    'Communicate directly with the university representatives through our portal.' => '',
    'Free admission counseling and guidance/supervision for the successful completion of the entire application process for GTU partner universities' => '',
    'GoToUniversity?' => '',
    'Journey' => '',
    'Mission' => '',
    'Our' => '',
    'Quick comparison and evaluation of different programs in terms of fees, course structure, admission criteria, location and career options.' => '',
    'Regular newsletters to keep you updated with university deadlines, latest news on education, universities and prevailing trends.' => '',
    'Top career and admission consultants from around the world on one portal, so that you can choose the one who best matches your needs.' => '',
    'Understanding how overwhelming the process of applying to 
the right university can be, our goal is simple yet comprehensive: we provide a platform that connects students with universities, empowering the students to make the right choice with minimum effort, while providing universities with constant updates on students needs and latest trends.' => '',
    'Vision' => '',
    'We achieve this purpose in two ways:' => '',
    'Why' => '',
    'You are assigned a consultant and given access to a user-friendly system that provides you with complete clarity on the tasks that need to be completed, as well as receive alerts and reminders from your consultant to ensure the entire process is smooth and stress-free.' => '',
];
